---
title: "data checks"
format: html
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

```{r, echo=FALSE,message = FALSE, warning = FALSE}
library(here)
library(DBI)
library(RPostgres)
library(tidyverse)
library(networkD3)
library(htmlwidgets)
library(htmltools)
library(sankeyD3) # Not on CRAN, but here <https://github.com/fbreitwieser/sankeyD3>
library(scales)
library(ggsci)
library(cowplot)
library(roadoi)
library(rcrossref)
```

# Verify number of missing green tags via KB

```{sql, connection=kb_con}
select sum(count) as total_count
from (
    select scp04_item_id, scp04_oa_status, scp07_oa_status, count(*) as count
    from unigsdoerner.scp_shared_corpus ssc
    where ssc.scp04_oa_status ~ 'repositoryvor|repositoryam' and ssc.scp07_oa_status !~ 'repositoryvor|repositoryam'
    group by scp04_item_id, scp04_oa_status, scp07_oa_status
) as subquery;
```

# fetch Unpaywall OA info

```{r}
green_none_0407_raw <- oadoi_fetch(dois = doi_sample_0407, email = Sys.getenv("roadoi_email"), .progress = "text")
```


```{r}
load(here("green_none_0407_raw.RData"))
load(here("green_none_0710_raw.RData"))
```

```{r}
green_none_0407 <- green_none_0407_raw %>%
  select(doi, oa_status, has_repository_copy,oa_locations) %>%
  unnest(oa_locations, keep_empty = TRUE) %>%
  select(doi, oa_status, has_repository_copy, is_best, host_type)

write_csv(green_none_0407, here("green_none_0407.csv"))
```

```{r}
green_none_0710_raw <- oadoi_fetch(dois = doi_sample_0710, email = Sys.getenv("roadoi_email"), .progress = "text")

green_none_0710 <- green_none_0710_raw %>%
  select(doi, oa_status, has_repository_copy,oa_locations) %>%
  unnest(oa_locations, keep_empty = TRUE) %>%
  select(doi, oa_status, has_repository_copy, is_best, host_type)

write_csv(green_none_0710, here("green_none_0710.csv"))
```

# Analyse Unpaywall OA info

```{r}
green_none_0407 <- read_csv(here("green_none_0407.csv"))
green_none_0710 <- read_csv(here("green_none_0710.csv"))
```


```{r}
green_none_0407 %>%
  summarise(n=n_distinct(doi))

green_none_0407 %>%
  group_by(has_repository_copy) %>%
  summarise(n = n_distinct(doi))

green_none_0407 %>%
  filter(host_type == "repository") %>%
  group_by(oa_status, has_repository_copy, host_type) %>%
  summarise(n= n_distinct(doi)) %>%
  arrange(desc(n))
```

```{r}
upw_0407_recopy <- green_none_0407 %>%
  group_by(has_repository_copy) %>%
  summarise(count= n_distinct(doi)) %>%
  mutate(pct = formatC(round(count/sum(count) *100,2), format = "f", digits = 2)) %>%
  arrange(desc(count)) %>%
  mutate(count = formatC(count, format = "d", big.mark = ","))
```

```{r}
upw_0407_host <- green_none_0407 %>%
  group_by(oa_status,has_repository_copy,host_type) %>%
  summarise(count= n_distinct(doi)) %>%
  filter(host_type == "repository") %>%
  ungroup() %>%
  mutate(pct = formatC(round(count/sum(count) *100,2), format = "f", digits = 2)) %>%
  arrange(desc(count)) %>%
  mutate(count = formatC(count, format = "d", big.mark = ","))
```

```{r}
write_csv(upw_0407_recopy, here("upw_0407_recopy.csv"))
write_csv(upw_0407_host, here("upw_0407_host.csv"))
```

```{r}
save(upw_0407_recopy,file = here("upw_0407_recopy.RData"))
save(upw_0407_host,file = here("upw_0407_host.RData"))
```


```{r}
green_none_0710 %>%
  summarise(n=n_distinct(doi))

green_none_0710 %>%
  group_by(has_repository_copy) %>%
  summarise(n = n_distinct(doi))

green_none_0710 %>%
  filter(host_type == "repository") %>%
  group_by(oa_status, has_repository_copy, host_type) %>%
  summarise(n= n_distinct(doi)) %>%
  arrange(desc(n))
```


```{r}
upw_0710_recopy <- green_none_0710 %>%
  group_by(has_repository_copy) %>%
  summarise(count= n_distinct(doi)) %>%
  mutate(pct = formatC(round(count/sum(count) *100,2), format = "f", digits = 2)) %>%
  arrange(desc(count)) %>%
  mutate(count = formatC(count, format = "d", big.mark = ","))
```

```{r}
upw_0710_host <- green_none_0710 %>%
  group_by(oa_status,has_repository_copy,host_type) %>%
  summarise(count= n_distinct(doi)) %>%
  filter(host_type == "repository") %>%
  ungroup() %>%
  mutate(pct = formatC(round(count/sum(count) *100,2), format = "f", digits = 2)) %>%
  arrange(desc(count)) %>%
  mutate(count = formatC(count, format = "d", big.mark = ","))
```


```{r}
write_csv(upw_0710_recopy, here("upw_0710_recopy.csv"))
write_csv(upw_0710_host, here("upw_0710_host.csv"))
```

```{r}
save(upw_0710_recopy,file = here("upw_0710_recopy.RData"))
save(upw_0710_host,file = here("upw_0710_host.RData"))
```